# -*- coding: utf-8 -*-
"""TFG SENSOR 4 v7 (normalización y cambio de función de activación)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19xtMLh_H4rxMjZc5R0ovJIOpSDICjz0f

#AUTOENCODER PARA DETECTAR ANOMALÍAS EN ESTRUCTURAS

## LIBRERÍAS
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, regularizers
from matplotlib import pyplot as plt
from tensorflow.keras.layers import Conv1D, Conv1DTranspose, Dense, Flatten, Reshape, Dropout
from tensorflow.keras.models import Sequential

from sklearn.metrics import mean_squared_error
def rmse(y,yprime):
    return np.sqrt(mean_squared_error(y,yprime))

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')

! ls
# %cd /content/drive/MyDrive/Colab\ Notebooks/Sensor4
! ls
! pwd

"""##**SENSOR 4**

"""

sensor4_s = pd.read_excel("PROBETA1_BASELINE_VEDIT_sensor4_AUTOENCODER.xlsx")
print(sensor4_s.head())

min_reference_b = sensor4_s.min().min()
max_reference_b = sensor4_s.max().max()
min = min_reference_b
max = max_reference_b
print(max)
print(min)

"""

## DETERMINACIÓN DE LA REFERRENCIA PARA LA NORMALIZACIÓN DE DATOS
"""

testS4_pc1_s = pd.read_excel("PROBETA1_PASO_CARGA_1_sensor4_AUTOENCODER.xlsx")
min_reference_1 = testS4_pc1_s.min().min()
max_reference_1 = testS4_pc1_s.max().max()
print(max_reference_1)
print(min_reference_1)
if max_reference_1 > max :
  max = max_reference_1
  min = min_reference_1
print(max)
print(min)

testS4_pc2_s = pd.read_excel("PROBETA1_PASO_CARGA_2_sensor4_AUTOENCODER.xlsx")
min_reference_2 = testS4_pc2_s.min().min()
max_reference_2 = testS4_pc2_s.max().max()
print(max_reference_2)
print(min_reference_2)
if max_reference_2 > max :
  max = max_reference_2
  min = min_reference_2
print(max)
print(min)

testS4_pc3_s = pd.read_excel("PROBETA1_PASO_CARGA_3_sensor4_AUTOENCODER.xlsx")
min_reference_3 = testS4_pc3_s.min().min()
max_reference_3 = testS4_pc3_s.max().max()
print(max_reference_3)
print(min_reference_3)
if max_reference_3 > max :
  max = max_reference_3
  min = min_reference_3
print(max)
print(min)

testS4_pc4_s = pd.read_excel("PROBETA1_PASO_CARGA_4_sensor4_AUTOENCODER.xlsx")
min_reference_4 = testS4_pc4_s.min().min()
max_reference_4 = testS4_pc4_s.max().max()
print(max_reference_4)
print(min_reference_4)
if max_reference_4 > max :
  max = max_reference_4
  min = min_reference_4
print(max)
print(min)

testS4_pc5_s = pd.read_excel("PROBETA1_PASO_CARGA_5_sensor4_AUTOENCODER.xlsx")
min_reference_5 = testS4_pc5_s.min().min()
max_reference_5 = testS4_pc5_s.max().max()
print(max_reference_5)
print(min_reference_5)
if max_reference_5 > max :
  max = max_reference_5
  min = min_reference_5
print(max)
print(min)

testS4_pc6_s = pd.read_excel("PROBETA1_PASO_CARGA_6_VIGA_ROTA_sensor4_AUTOENCODER.xlsx")
min_reference_6 = testS4_pc6_s.min().min()
max_reference_6 = testS4_pc6_s.max().max()
print(max_reference_6)
print(min_reference_6)
if max_reference_6 > max :
  max = max_reference_6
  min = min_reference_6
print(max)
print(min)

"""## GRÁFICA DE LOS DATOS"""

plt.plot(sensor4_s['P_  1'], label = 'Baseline')
plt.plot(testS4_pc1_s['PP1_1'], label = 'Paso de carga 1')
plt.plot(testS4_pc2_s['PP2_1'], label = 'Paso de carga 2')
plt.plot(testS4_pc3_s['PP3_1'], label = 'Paso de carga 3')
plt.plot(testS4_pc4_s['PP4_1'], label = 'Paso de carga 4')
plt.plot(testS4_pc5_s['PP5_1'], label = 'Paso de carga 5')
plt.title('Impedances for Different Load Steps not including the state of rupture')
plt.legend()
plt.show()

"""## NORMALIZACIÓN DE LOS DATOS"""

sensor4 = (sensor4_s - min) / (max-min)

print(sensor4.head())

testS4_pc1_n = (testS4_pc1_s - min) / (max-min)
testS4_pc1_n2 = np.transpose(testS4_pc1_n)
testS4_pc1 = testS4_pc1_n2.values.reshape((testS4_pc1_n2.shape[0], testS4_pc1_n2.shape[1], 1))
print(testS4_pc1)
print(testS4_pc1.shape)

testS4_pc2_n = (testS4_pc2_s - min) / (max-min)
testS4_pc2_n2 = np.transpose(testS4_pc2_n)
testS4_pc2 = testS4_pc2_n2.values.reshape((testS4_pc2_n2.shape[0], testS4_pc2_n2.shape[1], 1))
print(testS4_pc2)
print(testS4_pc2.shape)

testS4_pc3_n = (testS4_pc3_s - min) / (max-min)
testS4_pc3_n2 = np.transpose(testS4_pc3_n)
testS4_pc3 = testS4_pc3_n2.values.reshape((testS4_pc3_n2.shape[0], testS4_pc3_n2.shape[1], 1))
print(testS4_pc3)
print(testS4_pc3.shape)

testS4_pc4_n = (testS4_pc4_s - min) / (max-min)
testS4_pc4_n2 = np.transpose(testS4_pc4_n)
testS4_pc4 = testS4_pc4_n2.values.reshape((testS4_pc4_n2.shape[0], testS4_pc4_n2.shape[1], 1))
print(testS4_pc4)
print(testS4_pc4.shape)

testS4_pc5_n = (testS4_pc5_s - min) / (max-min)
testS4_pc5_n2 = np.transpose(testS4_pc5_n)
testS4_pc5 = testS4_pc5_n2.values.reshape((testS4_pc5_n2.shape[0], testS4_pc5_n2.shape[1], 1))
print(testS4_pc5)
print(testS4_pc5.shape)

testS4_pc6_n = (testS4_pc6_s - min) / (max-min)
testS4_pc6_n2 = np.transpose(testS4_pc6_n)
testS4_pc6 = testS4_pc6_n2.values.reshape((testS4_pc6_n2.shape[0], testS4_pc6_n2.shape[1], 1))
print(testS4_pc6)
print(testS4_pc6.shape)

plt.plot(sensor4['P_  1'], label = 'Baseline')
plt.plot(testS4_pc1_n['PP1_1'], label = 'Paso de carga 1')
plt.plot(testS4_pc2_n['PP2_1'], label = 'Paso de carga 2')
plt.plot(testS4_pc3_n['PP3_1'], label = 'Paso de carga 3')
plt.plot(testS4_pc4_n['PP4_1'], label = 'Paso de carga 4')
plt.plot(testS4_pc5_n['PP5_1'], label = 'Paso de carga 5')
plt.title('Impedances normalized for Different Load Steps not including the state of rupture')
plt.legend()
plt.show()

"""## CREACIÓN DE LOS GRUPOS APRENDIZAJE Y TEST




"""

sensor4_t = np.transpose(sensor4)
print(sensor4_t.head())

from sklearn.model_selection import train_test_split
trainS4,testS4 = train_test_split(sensor4_t,train_size=0.75,random_state=111)
print(trainS4)

"""## PREPARACIÓN DATOS DE ENTRENAMIENTO


"""

trainS4 = trainS4.values.reshape((trainS4.shape[0], trainS4.shape[1], 1))
inputS4_shape = trainS4.shape[1:]
print(inputS4_shape)

trainS4.shape

trainS4.shape[0:2]

"""## RED NEURONAL

We will build a convolutional reconstruction autoencoder model. The model will
take input of shape `(batch_size, sequence_length, num_features)` and return
output of the same shape. In this case, `sequence_length` is 288 and
`num_features` is 1.
"""

modelS4 = Sequential()
modelS4.add(Conv1D(filters=64, kernel_size=5, activation='PReLU', padding='same',  kernel_regularizer=regularizers.l2(0.5), input_shape=inputS4_shape))
modelS4.add(Conv1D(filters=64, kernel_size=3, activation='PReLU', padding='same',kernel_regularizer=regularizers.l2(0.5)))
modelS4.add(Conv1D(filters=32, kernel_size=3, activation='PReLU', padding='same',kernel_regularizer=regularizers.l2(0.5)))
modelS4.add(Conv1D(filters=16, kernel_size=3, activation='PReLU', padding='same', kernel_regularizer=regularizers.l2(0.5)))
modelS4.add(Conv1D(filters=8, kernel_size=3, activation='PReLU', padding='same',kernel_regularizer=regularizers.l2(0.5)))

modelS4.add(Conv1DTranspose(filters=8, kernel_size=3, activation='PReLU', padding='same',kernel_regularizer=regularizers.l2(0.5)))
modelS4.add(Conv1DTranspose(filters=16, kernel_size=5, activation='PReLU', padding='same',kernel_regularizer=regularizers.l2(0.5)))
modelS4.add(Conv1DTranspose(filters=32, kernel_size=5, activation='PReLU', padding='same',kernel_regularizer=regularizers.l2(0.5)))
modelS4.add(Conv1DTranspose(filters=64, kernel_size=5, activation='PReLU', padding='same',kernel_regularizer=regularizers.l2(0.5)))
modelS4.add(Conv1DTranspose(filters=64, kernel_size=10, activation='PReLU', padding='same',kernel_regularizer=regularizers.l2(0.5)))

modelS4.add(Conv1D(filters=inputS4_shape[-1], kernel_size=3, activation='linear', padding='same'))

# Compilar el modelo
modelS4.compile(optimizer='adam', loss='mean_squared_error', metrics=['RootMeanSquaredError'])



trainS4_pred_SE = modelS4.predict(trainS4)
plt.plot(trainS4[0], label = 'Valor de la parte real de las impedancias de entrenamiento')
plt.plot(trainS4_pred_SE[0], label = 'Valor predecido de la parte real de las impedancias de entrenamiento')
plt.show()

"""## ENTRENAMIENTO DEL MODELO



"""

callback = tf.keras.callbacks.EarlyStopping(monitor = 'val_loss', patience = 5)
historyS4 = modelS4.fit(trainS4, trainS4, epochs=45, batch_size=5, validation_data=(testS4, testS4), callbacks = [callback])

"""Let's plot training and validation loss to see how the training went."""

plt.plot(historyS4.history["loss"], label="Training Loss")
plt.plot(historyS4.history["val_loss"], label="Validation Loss")
plt.legend()
plt.show()

optimizer = modelS4.optimizer
learning_rate = optimizer.learning_rate.numpy()
print("Tasa de aprendizaje:", learning_rate)

"""## DETECCIÓN DE ANOMALÍAS

We will detect anomalies by determining how well our model can reconstruct
the input data.


1.   Find RMSE loss on training samples.
2.   Find max RMSE loss value. This is the worst our model has performed trying
to reconstruct a sample. We will make this the `threshold` for anomaly
detection.
3.   If the reconstruction loss for a sample is greater than this `threshold`
value then we can infer that the model is seeing a pattern that it isn't
familiar with. We will label this sample as an `anomaly`.

"""

# Get train RMSE loss.
trainS4_pred = modelS4.predict(trainS4)
trainS4_pred2 = trainS4_pred.reshape((trainS4_pred.shape[0], trainS4_pred.shape[1]))
trainS4_2 = trainS4.reshape((trainS4.shape[0], trainS4.shape[1]))

trainS4_rmse_loss = rmse(trainS4_pred2,trainS4_2)

# plt.hist(trainS4_rmse_loss, bins=50)
# plt.xlabel("Train RMSE loss")
# plt.ylabel("No of samples")
# plt.show()

# # Get reconstruction loss threshold.
# thresholdS4 = np.max(trainS4_rmse_loss)
# print("Reconstruction error threshold: ", thresholdS4)

"""### Compare recontruction

Just for fun, let's see how our model has recontructed the first sample.
This is the 288 timesteps from day 1 of our training dataset.
"""

# Checking how the first sequence is learnt
plt.plot(trainS4[0])
plt.plot(trainS4_pred[0])
plt.show()

"""### Prepare test data"""

# fig, ax = plt.subplots()
# testS4.plot(legend=False, ax=ax)
# plt.show()
testS4 = testS4.values.reshape((testS4.shape[0], testS4.shape[1], 1))
# Get test RMSE loss.

testS4_pred = modelS4.predict(testS4)
testS4_pred2 =  testS4_pred.reshape((testS4_pred.shape[0], testS4_pred.shape[1]))
testS4_2 =  testS4.reshape((testS4.shape[0], testS4.shape[1]))
testS4_rmse_loss = rmse(testS4_pred2,testS4_2)


# plt.hist(testS4_rmse_loss, bins=50)
# plt.xlabel("test RMSE loss")
# plt.ylabel("No of samples")
# plt.show()

# # Detect all the samples which are anomalies.
# anomaliesS4 = testS4_rmse_loss > thresholdS4
# print("Number of anomaly samples: ", np.sum(anomaliesS4))
# print("Indices of anomaly samples: ", np.where(anomaliesS4))

plt.plot(testS4[0])
plt.plot(testS4_pred[0])
plt.show()

print(testS4_rmse_loss)

"""###PASO DE CARGA 1


"""

testS4_pc1_pred = modelS4.predict(testS4_pc1)
testS4_pc1_pred.shape

plt.plot(testS4_pc1[0], label='Original')
plt.plot(testS4_pc1_pred[0], label='Reconstructed')
plt.show()

testS4_pc1_pred2 =  testS4_pc1_pred.reshape((testS4_pc1_pred.shape[0], testS4_pc1_pred.shape[1]))
testS4_pc1_2 =  testS4_pc1.reshape((testS4_pc1.shape[0], testS4_pc1.shape[1]))
testS4_pc1_rmse_loss = rmse(testS4_pc1_pred2,testS4_pc1_2)



# plt.hist(testS4_pc1_rmse_loss, bins=50)
# plt.xlabel("test RMSE loss")
# plt.ylabel("No of samples")
# plt.show()

# # Detect all the samples which are anomalies.
# anomaliesS4_pc1 = testS4_pc1_rmse_loss > thresholdS4
# print("Number of anomaly samples: ", np.sum(anomaliesS4_pc1))
# print("Indices of anomaly samples: ", np.where(anomaliesS4_pc1))

print(testS4_pc1_rmse_loss)

# plt.scatter(1, trainS4_rmse_loss, label='Entrenamiento')
# plt.scatter(1, testS4_rmse_loss, label='Validación')
# plt.scatter(1, testS4_pc1_rmse_loss, label='Paso de carga 1')
# plt.axhline(y=thresholdS4, color='r', linestyle='--')
# plt.xlabel('Ensayos')
# plt.ylabel('RMSE')
# plt.legend()
# plt.show()

"""## PASO DE CARGA 1 CON VALORES ATÍPICOS"""

import random

testS4_pc1_n2_2 = testS4_pc1_n2.to_numpy() if isinstance(testS4_pc1_n2, pd.DataFrame) else testS4_pc1_n2
testS4_pc1_VA = testS4_pc1_n2_2.copy()
slice_to_modify = testS4_pc1_VA[:, 200:400]
random_values = np.random.randint(2, size=slice_to_modify.shape)
testS4_pc1_VA[:, 200:400] = random_values
print(testS4_pc1_VA)
plt.plot(testS4_pc1_VA.ravel()[0:7201], label='Paso de carga modificado')
plt.show()
print(testS4_pc1_VA.shape)

testS4_pc1_VA = testS4_pc1_VA.reshape((testS4_pc1_VA.shape[0], testS4_pc1_VA.shape[1], 1))
testS4_pc1_VA_pred = modelS4.predict(testS4_pc1_VA)
testS4_pc1_VA_pred.shape

plt.plot(testS4_pc1_VA[0], label='Paso de carga modificado')
plt.plot(testS4_pc1_VA_pred[0], label='Predicción del paso de carga modificado')
plt.legend()
plt.show()

"""###PASO DE CARGA 2"""

testS4_pc2_pred = modelS4.predict(testS4_pc2)
testS4_pc2_pred2 =  testS4_pc2_pred.reshape((testS4_pc2_pred.shape[0], testS4_pc2_pred.shape[1]))
testS4_pc2_2 =  testS4_pc2.reshape((testS4_pc2.shape[0], testS4_pc2.shape[1]))
testS4_pc2_rmse_loss = rmse(testS4_pc2_pred2,testS4_pc2_2)



# plt.hist(testS4_pc2_rmse_loss, bins=50)
# plt.xlabel("test RMSE loss")
# plt.ylabel("No of samples")
# plt.show()

# # Detect all the samples which are anomalies.
# anomaliesS4_pc2 = testS4_pc2_rmse_loss > thresholdS4
# print("Number of anomaly samples: ", np.sum(anomaliesS4_pc2))
# print("Indices of anomaly samples: ", np.where(anomaliesS4_pc2))

plt.plot(testS4_pc2[0], label='Original')
plt.plot(testS4_pc2_pred[0], label='Reconstructed')
plt.show()

# plt.scatter(1, trainS4_rmse_loss, label='Entrenamiento')
# plt.scatter(1, testS4_rmse_loss, label='Validación')
# plt.scatter(1, testS4_pc2_rmse_loss, label='Paso de carga 2')
# plt.axhline(y=thresholdS4, color='r', linestyle='--')
# plt.xlabel('Ensayos')
# plt.ylabel('RMSE')
# plt.legend()
# plt.show()

"""###PASO DE CARGA 3

"""

testS4_pc3_pred = modelS4.predict(testS4_pc3)
testS4_pc3_pred2 =  testS4_pc3_pred.reshape((testS4_pc3_pred.shape[0], testS4_pc3_pred.shape[1]))
testS4_pc3_2 =  testS4_pc3.reshape((testS4_pc3.shape[0], testS4_pc3.shape[1]))
testS4_pc3_rmse_loss = rmse(testS4_pc3_pred2, testS4_pc3_2)



# plt.hist(testS4_pc3_rmse_loss, bins=50)
# plt.xlabel("test RMSE loss")
# plt.ylabel("No of samples")
# plt.show()

# # Detect all the samples which are anomalies.
# anomaliesS4_pc3 = testS4_pc3_rmse_loss > thresholdS4
# print("Number of anomaly samples: ", np.sum(anomaliesS4_pc3))
# print("Indices of anomaly samples: ", np.where(anomaliesS4_pc3))

plt.plot(testS4_pc3[0], label='Original')
plt.plot(testS4_pc3_pred[0], label='Reconstructed')
plt.show()

# plt.scatter(1, trainS4_rmse_loss, label='Entrenamiento')
# plt.scatter(1, testS4_rmse_loss, label='Validación')
# plt.scatter(1, testS4_pc3_rmse_loss, label='Paso de carga 3')
# plt.axhline(y=thresholdS4, color='r', linestyle='--')
# plt.xlabel('Ensayos')
# plt.ylabel('RMSE')
# plt.legend()
# plt.show()

"""###PASO DE CARGA 4"""

testS4_pc4_pred = modelS4.predict(testS4_pc4)
testS4_pc4_pred2 =  testS4_pc4_pred.reshape((testS4_pc4_pred.shape[0], testS4_pc4_pred.shape[1]))
testS4_pc4_2 =  testS4_pc4.reshape((testS4_pc4.shape[0], testS4_pc4.shape[1]))
testS4_pc4_rmse_loss = rmse(testS4_pc4_pred2, testS4_pc4_2)



# plt.hist(testS4_pc4_rmse_loss, bins=50)
# plt.xlabel("test RMSE loss")
# plt.ylabel("No of samples")
# plt.show()

# # Detect all the samples which are anomalies.
# anomaliesS4_pc4 = testS4_pc4_rmse_loss > thresholdS4
# print("Number of anomaly samples: ", np.sum(anomaliesS4_pc4))
# print("Indices of anomaly samples: ", np.where(anomaliesS4_pc4))

plt.plot(testS4_pc4[0], label='Original')
plt.plot(testS4_pc4_pred[0], label='Reconstructed')
plt.show()

# plt.scatter(1, trainS4_rmse_loss, label='Entrenamiento')
# plt.scatter(1, testS4_rmse_loss, label='Validación')
# plt.scatter(1, testS4_pc4_rmse_loss, label='Paso de carga 4')
# plt.axhline(y=thresholdS4, color='r', linestyle='--')
# plt.xlabel('Ensayos')
# plt.ylabel('RMSE')
# plt.legend()
# plt.show()

"""###PASO DE CARGA 5"""

testS4_pc5_pred = modelS4.predict(testS4_pc5)
testS4_pc5_pred2 =  testS4_pc5_pred.reshape((testS4_pc5_pred.shape[0], testS4_pc5_pred.shape[1]))
testS4_pc5_2 =  testS4_pc5.reshape((testS4_pc5.shape[0], testS4_pc5.shape[1]))
testS4_pc5_rmse_loss = rmse(testS4_pc5_pred2,testS4_pc5_2)



# plt.hist(testS4_pc5_rmse_loss, bins=50)
# plt.xlabel("test RMSE loss")
# plt.ylabel("No of samples")
# plt.show()

# # Detect all the samples which are anomalies.
# anomaliesS4_pc5 = testS4_pc5_rmse_loss > thresholdS4
# print("Number of anomaly samples: ", np.sum(anomaliesS4_pc5))
# print("Indices of anomaly samples: ", np.where(anomaliesS4_pc5))

plt.plot(testS4_pc5[0], label='Original')
plt.plot(testS4_pc5_pred[0], label='Reconstructed')
plt.show()

# plt.scatter(1, trainS4_rmse_loss, label='Entrenamiento')
# plt.scatter(1, testS4_rmse_loss, label='Validación')
# plt.scatter(1, testS4_pc5_rmse_loss, label='Paso de carga 5')
# plt.axhline(y=thresholdS4, color='r', linestyle='--')
# plt.xlabel('Ensayos')
# plt.ylabel('RMSE')
# plt.legend()
# plt.show()

"""

###PASO DE CARGA 6"""

testS4_pc6_pred = modelS4.predict(testS4_pc6)
testS4_pc6_pred2 =  testS4_pc6_pred.reshape((testS4_pc6_pred.shape[0], testS4_pc6_pred.shape[1]))
testS4_pc6_2 =  testS4_pc6.reshape((testS4_pc6.shape[0], testS4_pc6.shape[1]))
testS4_pc6_rmse_loss = rmse(testS4_pc6_pred2, testS4_pc6_2)


# plt.hist(testS4_pc6_rmse_loss, bins=50)
# plt.xlabel("test RMSE loss")
# plt.ylabel("No of samples")
# plt.show()

# # Detect all the samples which are anomalies.
# anomaliesS4_pc6 = testS4_pc6_rmse_loss > thresholdS4
# print("Number of anomaly samples: ", np.sum(anomaliesS4_pc6))
# print("Indices of anomaly samples: ", np.where(anomaliesS4_pc6))

plt.plot(testS4_pc6[0], label='Original')
plt.plot(testS4_pc6_pred[0], label='Reconstructed')
plt.show()

# plt.scatter(1, trainS4_rmse_loss, label='Entrenamiento')
# plt.scatter(1, testS4_rmse_loss, label='Validación')
# plt.scatter(1, testS4_pc6_rmse_loss, label='Paso de carga 6')
# plt.axhline(y=thresholdS4, color='r', linestyle='--')
# plt.xlabel('Ensayos')
# plt.ylabel('RMSE')
# plt.legend()
# plt.show()

plt.bar(-1, trainS4_rmse_loss, label='Training')
plt.bar(0, testS4_rmse_loss, label='Validation')
plt.bar(1, testS4_pc1_rmse_loss, label='Paso de carga 1')
plt.bar(2, testS4_pc2_rmse_loss, label='Paso de carga 2')
plt.bar(3, testS4_pc3_rmse_loss, label='Paso de carga 3')
plt.bar(4, testS4_pc4_rmse_loss, label='Paso de carga 4')
plt.bar(5, testS4_pc5_rmse_loss, label='Paso de carga 5')
plt.xlabel('Load Steps')
plt.ylabel('RMSE')
plt.title('RMSE for Different Load Steps')
plt.legend()
plt.show()

plt.bar(-1, trainS4_rmse_loss, label='Training')
plt.bar(0, testS4_rmse_loss, label='Validation')
plt.bar(1, testS4_pc1_rmse_loss, label='Paso de carga 1')
plt.bar(2, testS4_pc2_rmse_loss, label='Paso de carga 2')
plt.bar(3, testS4_pc3_rmse_loss, label='Paso de carga 3')
plt.bar(4, testS4_pc4_rmse_loss, label='Paso de carga 4')
plt.bar(5, testS4_pc5_rmse_loss, label='Paso de carga 5')
plt.bar(6, testS4_pc6_rmse_loss, label='Paso de carga 6')
plt.xlabel('Load Steps')
plt.ylabel('RMSE')
plt.title('RMSE for Different Load Steps')
plt.legend()
plt.show()